[build]
  base = "./"
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/**/*"]

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  GENERATE_SOURCEMAP = "false"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 