[build]
  base = "./"
  command = "npm install && cd client && npm install && npm run build"
  publish = "client/build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["functions/**/*"]

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 